 --- #YAML:1.0
name:         JSON-Any
abstract:     Provide a common API for JSON modules
author:
   - Chris Thompson <cthom@cpan.org>
   - Chris Prather <perigrin@cpan.org>
license: perl
version:      1.06
version_from: lib/JSON/Any.pm
installdirs:  site
requires:
    Test::More:                    0
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html